import pkg from '/Users/ahmedabdelwahid/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 390, height: 200 });
await page.goto('http://localhost:8000', { waitUntil: 'domcontentloaded', timeout: 15000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/header_prod.png' });
const headerHTML = await page.locator('header.top-bar').innerHTML();
console.log('Header:', headerHTML);
await browser.close();
