[variables]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.14"

[nix]
  enableCache = true

[packages]
  nodejs = "nodejs_20"
  python = "python314"
  pip = "pip"

[build]
  only = ["frontend/src", "frontend/package.json", "frontend/vite.config.js", "frontend/index.html", "web", "spot", "data", "main.py", "requirements.txt"]
